Repository italia/bootstrap-italia, pull requests merged in 2023-01, with the labels that each got.

#803 Fix issue #799
  src/scss/custom/_form-datepicker.scss
Labels: next-release

#791 remove node_modules prefix from scss import
  src/scss/bootstrap-italia-comuni.scss
  src/scss/bootstrap-italia.scss
Labels: next-release

#776 feat/colors adj
  src/scss/_variables.scss
  src/scss/custom/_accordion.scss
  src/scss/custom/_alert.scss
  src/scss/custom/_autocomplete.scss
  src/scss/custom/_avatar.scss
  src/scss/custom/_back-to-top.scss
  src/scss/custom/_bottomnav.scss
  src/scss/custom/_breadcrumb.scss
  src/scss/custom/_buttons.scss
  src/scss/custom/_calendar.scss
  src/scss/custom/_callout.scss
  src/scss/custom/_card.scss
  src/scss/custom/_carousel.scss
  src/scss/custom/_chips.scss
  src/scss/custom/_cookiebar.scss
  src/scss/custom/_dimmer.scss
  src/scss/custom/_dropdown.scss
  src/scss/custom/_footer.scss
  src/scss/custom/_form-datepicker.scss
  src/scss/custom/_form-input-file.scss
  src/scss/custom/_form-input-number.scss
  src/scss/custom/_form-password.scss
  src/scss/custom/_form-select.scss
  src/scss/custom/_forms.scss
  src/scss/custom/_linklist.scss
  src/scss/custom/_list.scss
  src/scss/custom/_masonry-loader.scss
  src/scss/custom/_megamenu.scss
  src/scss/custom/_modal.scss
  src/scss/custom/_notifications.scss
  src/scss/custom/_point-list.scss
  src/scss/custom/_popover.scss
  src/scss/custom/_progress-bars.scss
  src/scss/custom/_progress-donuts.scss
  src/scss/custom/_progress-spinners.scss
  src/scss/custom/_sections.scss
  src/scss/custom/_sidebar.scss
  src/scss/custom/_steppers.scss
  src/scss/custom/_tab.scss
  src/scss/custom/_timeline.scss
  src/scss/custom/_toolbar.scss
  src/scss/custom/_tooltip.scss
  src/scss/utilities/colors_vars.scss
Labels: next-release, 2.x, enhancement

#801 fix/torna_su_accessibile_798
  _includes/esempi/comuni/footer.html
  docs/menu-di-navigazione/torna-su.md
Labels: a11y, next-release, 2.x

#809 chore: upgrade to bootstrap 5.2.3
  .pa11yci
  _config.yml
  package-lock.json
  package.json
  publiccode.yml
  src/js/bootstrap-italia.entry.js
  src/js/plugins/notification.js
  src/js/plugins/tab.js
  src/scss/bootstrap-italia-comuni.scss
  src/scss/bootstrap-italia.scss
Labels: next-release

#819 Fixed wrong container max-width for XL breakpoint
  docs/organizzare-gli-spazi/griglie.md
Labels: bug

#817 fix(a11y): steppers
  docs/componenti/steppers.md
  src/scss/custom/_steppers.scss
Labels: next-release, 2.x

#811 fix(a11y): colors
  .pa11yci
  src/js/plugins/progress-donut.js
  src/scss/_variables.scss
  src/scss/custom/_alert.scss
  src/scss/custom/_buttons.scss
  src/scss/custom/_callout.scss
  src/scss/custom/_chips.scss
  src/scss/custom/_tab.scss
  src/scss/custom/_timeline.scss
  src/scss/utilities/colors_vars.scss
Labels: next-release

#804 [TS] Aggiunti i types
  .eslintrc.json
  package-lock.json
  package.json
  types/decs.d.ts
  types/index.d.ts
  types/plugins/accordion.d.ts
  types/plugins/alert.d.ts
  types/plugins/backToTop.d.ts
  types/plugins/button.d.ts
  types/plugins/carousel-bi.d.ts
  types/plugins/carousel.d.ts
  types/plugins/collapse.d.ts
  types/plugins/cookiebar.d.ts
  types/plugins/dimmer.d.ts
  types/plugins/dropdown.d.ts
  types/plugins/form-validate.d.ts
  types/plugins/form.d.ts
  types/plugins/forward.d.ts
  types/plugins/header-sticky.d.ts
  types/plugins/history-back.d.ts
  types/plugins/input-label.d.ts
  types/plugins/input-number.d.ts
  types/plugins/input-password.d.ts
  types/plugins/input-search-autocomplete.d.ts
  types/plugins/input.d.ts
  types/plugins/list.d.ts
  types/plugins/masonry.d.ts
  types/plugins/modal.d.ts
  types/plugins/navbar-collapsible.d.ts
  types/plugins/navscroll.d.ts
  types/plugins/notification.d.ts
  types/plugins/offcanvas.d.ts
  types/plugins/popover.d.ts
  types/plugins/progress-donut.d.ts
  types/plugins/scrollspy.d.ts
  types/plugins/select-autocomplete.d.ts
  types/plugins/sticky.d.ts
  types/plugins/tab.d.ts
  types/plugins/toast.d.ts
  types/plugins/tooltip.d.ts
  types/plugins/track-focus.d.ts
  types/plugins/transfer.d.ts
  types/plugins/upload-dragdrop.d.ts
Labels: next-release
