Repository italia/bootstrap-italia, pull requests merged in 2023-12, with the labels that each got.

#1043 fix: corretto bottone copia, escludo il numero della riga
  _includes/scripts.html
Labels: bug

#1042 fix: refactor lint spacing and newlines around files
  docs/componenti/alert.md
  docs/componenti/buttons.md
  docs/componenti/card.md
  docs/componenti/carousel.md
  docs/componenti/hero.md
  docs/componenti/modale.md
  docs/componenti/sticky.md
  docs/componenti/tab.md
  docs/componenti/timeline.md
  docs/esempi/comuni/index.html
  docs/esempi/comuni/template-amministrazione.html
  docs/esempi/comuni/template-area-personale-dettaglio-pratica.html
  docs/esempi/comuni/template-area-personale.html
  docs/esempi/comuni/template-argomenti-argomento.html
  docs/esempi/comuni/template-argomenti.html
  docs/esempi/comuni/template-documenti.html
  docs/esempi/comuni/template-homepage.html
  docs/esempi/comuni/template-novita-evento.html
  docs/esempi/comuni/template-novita-notizia.html
  docs/esempi/comuni/template-novita.html
  docs/esempi/comuni/template-risultato-ricerca.html
  docs/esempi/comuni/template-servizi-servizio.html
  docs/esempi/comuni/template-servizi.html
  docs/esempi/hero/index.html
  docs/esempi/navscroll/index.html
  docs/esempi/notifications/index.html
  docs/esempi/sticky-target/index.html
  docs/esempi/template-vuoto/index.html
  docs/form/transfer.md
  docs/menu-di-navigazione/footer.md
  docs/organizzare-i-contenuti/liste-di-immagini.md
  docs/organizzare-i-contenuti/liste.md
Labels: docs, enhancement

#1046 feat: new input with prepend icon
  docs/esempi/form/index.html
  docs/esempi/navscroll/index.html
  docs/esempi/template-vuoto/index.html
  docs/form/input.md
  docs/form/introduzione.md
  src/scss/custom/_forms.scss
  src/scss/custom/_just-validate.scss
Labels: next-release

#1037 fix: buttons vs anchors a11y
  docs/come-iniziare/modificare-componenti.md
  docs/componenti/affix.md
  docs/componenti/avatar.md
  docs/componenti/dropdown.md
  docs/componenti/modale.md
  docs/componenti/paginazione.md
  docs/form/transfer.md
  docs/menu-di-navigazione/header.md
  docs/menu-di-navigazione/megamenu.md
  docs/menu-di-navigazione/navscroll.md
  docs/menu-di-navigazione/sidebar.md
  docs/menu-di-navigazione/skiplinks.md
  docs/organizzare-i-contenuti/liste.md
Labels: a11y, next-release, enhancement

#1036 feat: new megamenu a11y
  docs/menu-di-navigazione/header.md
  docs/menu-di-navigazione/megamenu.md
  src/scss/_variables.scss
  src/scss/custom/_headernavbar.scss
  src/scss/custom/_headernavbartheme.scss
  src/scss/custom/_megamenu.scss
  src/scss/custom/_navigation.scss
  src/scss/custom/_navigationtheme.scss
Labels: bug, new feature, a11y, next-release

#1054 fix: closing brackets
  CONTRIBUTING.md
Labels: bug

#1053 fix: navbar mobile focus
  src/js/plugins/navbar-collapsible.js
Labels: bug, a11y
