Repository italia/bootstrap-italia, pull requests merged in 2023-05, with the labels that each got.

#890 chore: video player example API names
  docs/componenti/video-player.md
Labels: integration

#904 fix: footer color variables #893
  src/scss/utilities/colors_vars.scss
Labels: bug

#906 feat: buttons outline color variations
  docs/componenti/buttons.md
  src/scss/_functions.scss
  src/scss/custom/_buttons.scss
  src/scss/custom/mixins/_buttons.scss
Labels: enhancement
